# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myApp2' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myApp2
	pod 'FontAwesome.swift'
        pod 'Instructions', '~> 1.0.0'
	pod 'DatePickerDialog'
	pod 'Hue'

	
end
